# mqtt
# Git: https://gitlab.com/wistron-project/occ-mqtt
# Git Wiki：https://gitlab.com/wistron-project/occ-mqtt/wikis/home

# prod：
# test：
# _test
# _test_serverr
# _player_mqtt
# dev：

spring:
  profiles:
    active: _dev
logging:
  config: classpath:logback${spring.profiles.active}.xml
  level:
    root: INFO

---
spring.profiles: _dev
spring:
  profiles:
    include: _swpc_top_mqtt_mac,_test_server

---
spring.profiles: _test
spring:
  profiles:
    include: _player_mqtt,_test_server





##### Resource #####

---
spring:
  profiles: _test_server
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: -1000
security:
  basic:
    enabled: false
  user:
    name: apiUser
    password: fAy<J}BKAJIz+7)9gHfR


---
spring:
  profiles: _player_mqtt
mqtt:
  broker:
    mac:
    url: ssl://10.34.172.109:8883
    security:
      hasauth: false
      username: admin
      password: password
      hastls: true
      ca:
        path: /Users/aaron/develop/workspace/eclipse/wst-occ/occ-mqtt/src/main/resources/mqtt-player/ca.crt
      cert:
        path: /Users/aaron/develop/workspace/eclipse/wst-occ/occ-mqtt/src/main/resources/mqtt-player/client.crt
      key:
        path: /Users/aaron/develop/workspace/eclipse/wst-occ/occ-mqtt/src/main/resources/mqtt-player/client.key

    connect:
      timeout: 300
    keep:
      alive: 10
    qos: 0
    scriber:
      topic:
        motcspat: roadside/signalcontrol/motcspat
        priority: roadside/traffichandler/priority
        distance: roadside/traffichandler/cms

---
spring:
  profiles: _nchc_top_mqtt_mac
mqtt:
  broker:
    mac:
    url: ssl://iot.stois.nchc.tw:8884
    security:
      hasauth: false
      username: admin
      password: password
      hastls: true
      ca:
        path: /Users/aaron/develop/workspace/eclipse/wst-occ/occ-mqtt/src/main/resources/mqtt-top-nchc/iot_stois_broker_top_root_CA.crt
      cert:
        path: /Users/aaron/develop/workspace/eclipse/wst-occ/occ-mqtt/src/main/resources/mqtt-top-nchc/iot_stois_broker_top_client.crt
      key:
        path: /Users/aaron/develop/workspace/eclipse/wst-occ/occ-mqtt/src/main/resources/mqtt-top-nchc/iot_stois_broker_top_client.key
    connect:
      timeout: 300
    keep:
      alive: 10
    qos: 0
    scriber:
      topic:
        motcspat: roadside/signalcontrol/motcspat
        priority: roadside/traffichandler/priority
        distance: roadside/traffichandler/cms
        gbus: vehicle/report/gbus
        mkz: vehicle/report/mkz
        itri: vehicle/report/itri
        cht: vehicle/report/cht
        test: vehicle/report/test

---
spring:
  profiles: _swpc_top_mqtt_mac
mqtt:
  broker:
    mac:
    url: ssl://iot.stois.nchc.tw:3051
    security:
      hasauth: false
      username: admin
      password: password
      hastls: true
      ca:
        path: /Users/aaron/develop/workspace/eclipse/spring-cloud-aaron/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-top-swpc/ca.crt
      cert:
        path: /Users/aaron/develop/workspace/eclipse/spring-cloud-aaron/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-top-swpc/admin.crt
      key:
        path: /Users/aaron/develop/workspace/eclipse/spring-cloud-aaron/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-top-swpc/admin.key
    connect:
      timeout: 300
    keep:
      alive: 10
    qos: 0
    scriber:
      topic:
        motcspat: roadside/signalcontrol/motcspat
        priority: roadside/traffichandler/priority
        distance: roadside/traffichandler/cms
        gbus: vehicle/report/gbus
        mkz: vehicle/report/mkz
        itri: vehicle/report/itri
        cht: vehicle/report/cht
        test: vehicle/report/test