# aaron-mqtt-client-service 

# dev：
      #_nchc_top_mqtt

# test：
      # _player_mqtt                        
      
spring:
  profiles:
   active: _dev
logging:                       
       config: classpath:logback${spring.profiles.active}.xml     
       level:
            root: INFO

---
spring.profiles: _dev
spring:
    profiles: 
       include: _nchc_top_mqtt,_server

---
spring.profiles: _test 
spring:
    profiles: 
       include: _player_mqtt,_server

                           
##### Resource #####    

---
spring:
  profiles: _server 
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
 
---
spring:
  profiles: _nchc_top_mqtt
mqtt:
      broker:
             mac:
             url: ssl://iot.omega.smartiply.com:8883
             security:
                    hasauth: false
                    username: admin       
                    password: password
                    hastls: true
                    ca: 
                        path: /Users/Kevin/Agile-MAC/eclipseWorkspace-MAC/Spring-Cloud/Aaron-Cloud/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-top-nchc/DST_Root_CA_X3.pem
                        #path: C:\\mqtt\aaron-mqtt-client-service\src\main\resources\mqtt-top-nchc\DST_Root_CA_X3.pem
                    cert:
                        path: /Users/Kevin/Agile-MAC/eclipseWorkspace-MAC/Spring-Cloud/Aaron-Cloud/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-top-nchc/certificate.crt
                        #path: C:\\mqtt\aaron-mqtt-client-service\src\main\resources\mqtt-top-nchc\certificate.crt
                    key:
                        path: /Users/Kevin/Agile-MAC/eclipseWorkspace-MAC/Spring-Cloud/Aaron-Cloud/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-top-nchc/private.key
                        #path: C:\\mqtt\aaron-mqtt-client-service\src\main\resources\mqtt-top-nchc\private.key
             connect:
                     timeout: 300
             keep:
                  alive: 10
             qos: 0 
             scriber:
                     topic:
                           gbus: vehicle/report/gbus
                           mkz:  vehicle/report/mkz
                           itri: vehicle/report/itri
                           cht:  vehicle/report/cht
                           test: vehicle/report/test
                           
---
spring:
  profiles: _player_mqtt            
mqtt:
      broker:
             mac: 
             url: ssl://10.34.172.109:8883
             security:
                    hasauth: false
                    username: admin       
                    password: password
                    hastls: true
                    ca:
                         path: /Users/Kevin/Agile-MAC/eclipseWorkspace-MAC/Spring-Cloud/Aaron-Cloud/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-player/ca.crt
                         #path: C:\\mqtt\aaron-mqtt-client-service\src\main\resources\ca.crt
                    cert:
                         path: /Users/Kevin/Agile-MAC/eclipseWorkspace-MAC/Spring-Cloud/Aaron-Cloud/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-player/client.crt
                         #path: C:\\mqtt\aaron-mqtt-client-service\src\main\resources\client.crt
                    key:
                         path: /Users/Kevin/Agile-MAC/eclipseWorkspace-MAC/Spring-Cloud/Aaron-Cloud/mqtt/aaron-mqtt-client-service/src/main/resources/mqtt-player/client.key
                         #path: C:\\mqtt\aaron-mqtt-client-service\src\main\resources\client.key
             connect:
                     timeout: 300
             keep:
                  alive: 10
             qos: 0 
             scriber:
                     topic:
                           gbus: vehicle/report/gbus
                           mkz:  vehicle/report/ncku
                           itri: vehicle/report/itri
                           cht:  vehicle/report/cht
                           test: vehicle/report/test